services:
  web:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001" # Porta para testes Capybara
    environment:
      - RAILS_ENV=${RAILS_ENV:-development}
      - DATABASE_URL=postgresql://postgres:postgres@db/desconto_inss_${RAILS_ENV:-development}
      - REDIS_URL=redis://redis:6379/1
      - CAPYBARA_APP_HOST=http://web:3000
      - CAPYBARA_SERVER_PORT=3001
    volumes:
      - .:/app
      - /app/node_modules
      - /app/tmp
      - /app/public/packs
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  chrome:
    image: selenium/standalone-chrome:4.20.0
    shm_size: 1gb
    ports:
      - "4444:4444"
    profiles: ["test"] # Só inicia quando explicitamente ativado

  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: desconto_inss_${RAILS_ENV:-development}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
